version: "3.8"
services:
  nginx:
    image: docker.io/library/nginx:1.27.4-alpine
    container_name: nginx
    ports:
      - "8081:80"   # Using port 8080 on the host
      - "444:443"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf   # Removed :ro
      - ./data/dist:/usr/share/nginx/html                     # Explicitly pointing to dist folder
    restart: unless-stopped
